alias doc='cd /usr/local/texlive/2014/texmf-dist/doc/latex'
alias ij='ipython console --profile julia'
alias in='ipython notebook --profile julia'
alias la='ll --almost-all'
alias ll='ls -l --human-readable --no-group'
alias ml='/Applications/MATLAB_R2013b.app/bin/matlab -nodesktop'
alias pdfl='pdflatex -halt-on-error'
alias pdfLaTeX='pdflatex'
